services:
    postgresql:
        image: postgres:16
        environment:
            POSTGRES_DB: 'pgsql_db'
            POSTGRES_USER: 'pgsql_user'
            POSTGRES_PASSWORD: 'pgsql_pass'
            PGDATA: '/var/lib/postgresql/data/pgdata'
        volumes:
            - ./storage/postgresql/data:/var/lib/postgresql/data
            - ./docker/postgresql/database/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
            - ./docker/postgresql/scripts/healthcheck.sh:/usr/local/bin/healthcheck.sh
            - ./logs/postgresql:/var/log/postgresql
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "chmod +x docker/postgresql/healthcheck/healthcheck.sh && /usr/local/bin/healthcheck.sh"]
            interval: 1s
            timeout: 5s
            retries: 10

    adminer:
        image: adminer
        ports:
            - 8080:8080
        depends_on:
            - postgresql

    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        volumes:
            - ./logs/zookeeper:/var/log/kafka
        ports:
            - 2181:2181

    kafka:
        image: confluentinc/cp-kafka:latest
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        volumes:
            - ./logs/kafka:/var/log/kafka
        ports:
            - 9092:9092
        depends_on:
            - zookeeper

    kafdrop:
        image: obsidiandynamics/kafdrop
        restart: 'no'
        ports:
            - 9900:9000
        environment:
            KAFKA_BROKERCONNECT: kafka:9092
        depends_on:
            - zookeeper
            - kafka

    php:
        build:
            context: ./docker/php
            dockerfile: ./dockerfile
        volumes:
            - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/app-php.ini
            - ./logs/php:/var/log/php
            - ./app:/var/www/html
            - ./docker/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./logs/supervisor:/var/log/supervisor
        depends_on:
            - postgresql
            - zookeeper
            - kafka

    nginx:
        image: nginx:alpine
        volumes:
            - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx:/var/log/nginx
            - ./app:/var/www/html
        ports:
            - 80:80
        depends_on:
            - php
            - postgresql
            - zookeeper
            - kafka
